---
tap_install:
  values:
    profile: iterate
    ceip_policy_disclosed: true

    shared:
      ingress_domain: iterate.tap.raltaf.io
      image_registry:  
        project_path: "registry.harbor.learn.tapsme.org/tap-build"
    supply_chain: basic
    ootb_supply_chain_basic:
   

    namespace_provisioner:
      controller: false
      additional_sources:
      - git:
          url: ssh://git@github.com/pakiheart/tap-gitops
          ref: origin/main
          subPath: credentials
          secretRef:
            name: sync-git-ssh-3
            namespace: tanzu-sync
            create_export: true
        path: _ytt_lib/workload-creds
      - git:
          url: ssh://git@github.com/pakiheart/tap-gitops
          ref: origin/main
          subPath: additional_resources
          secretRef:
            name: sync-git-ssh-2
            namespace: tanzu-sync
            create_export: true
        path: _ytt_lib/workload-additional-resources
      gitops_install:
        url: ssh://git@github.com/pakiheart/tap-gitops
        ref: origin/main
        subPath: ns-provisioner
        secretRef:
          name: sync-git-ssh
          namespace: tanzu-sync
          # create_export: true
      import_data_values_secrets:
      - name: tenant-secrets
        namespace: tap-install
        create_export: true
      overlay_secrets:
      - name: workload-git-ssh-overlay
        namespace: tap-install
        create_export: true

    appliveview_connector:
      backend:
        ingressEnabled: true
        host: appliveview.view.tap.raltaf.io
    cnrs:
      domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"
    api_auto_registration:
      tap_gui_url: "https://tap-gui.view.tap.raltaf.io"
      cluster_name: iterate      
