---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: sync-git-ssh
  namespace: tanzu-sync
  annotations:
    kapp.k14s.io/change-group: se/sync-git-ssh
    kapp.k14s.io/change-rule.0: "upsert after eso/tap-sensitive-values"  
spec:
  toNamespaces:
  - "*"

---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: sync-git-ssh
  namespace: tap-install
spec:
  fromNamespace: tanzu-sync
